# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:    Adooylabs
tagline:          'Softwares and Startups'
description:    "I'm Audee Velasco. A ruby developer who is also learning other bunch of stuff like AngularJS, Objective-C and Swift; Art and Photography; Business and Entreprenuership."
url:              http://blog.adooylabs.com
baseurl:          /

author:
  name:  Audee Velasco
  url: https://twitter.com/adooylabs

paginate:         5

# Custom vars
version:         1.1.0
